AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for Cognito User Pool and IAM Policy"

Parameters:
  UserPoolName:
    Type: String
    Description: Name of the user pool
    Default: my-user-pool
  AppClientName:
    Type: String
    Description: Name of the app client
    Default: my-app-client
  ReplyEmailAddress:
    Type: String
    Description: Email address to send from (reply-to address)
  VerificationSubject:
    Type: String
    Description: Subject of the email verification message
    Default: "Verify your email for MyApp"

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      EmailVerificationSubject: !Ref VerificationSubject
      EmailVerificationMessage: "Please verify your email address by entering the following code: {####}"
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
        ReplyToEmailAddress: !Ref ReplyEmailAddress
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Ref AppClientName
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_CUSTOM_AUTH
      PreventUserExistenceErrors: ENABLED

Outputs:
  UserPoolId:
    Description: The ID of the user pool
    Value: !Ref CognitoUserPool
  UserPoolArn:
    Description: The ARN of the user pool
    Value: !GetAtt CognitoUserPool.Arn
  UserPoolClientId:
    Description: The ID of the user pool client
    Value: !Ref CognitoUserPoolClient
