Port: 9050
UserPoolRegion: "us-east-1"
UserPoolClientId: "xxxxxxxxxxxxxxxxxxxxxxxxxx"
UserPoolDomain: "mud-user-pool"
UserPoolId: "us-east-1_xxxxxxxxx"
UserPoolArn: "arn:aws:cognito-idp:us-east-1:999999999999:userpool/us-east-1_xxxxxxxxx"
UserPoolClientSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
DataFile: "./data.bolt"
Balance: 0.25
AutoSave: 5
StartingHealth: 10
StartingEssence: 3