Aws:
  Region: us-east-1
Cognito:
  UserPoolId: us-east-1_xxxxxxxxx
  UserPoolClientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  UserPoolClientId: xxxxxxxxxxxxxxxxxxxxxxxxxx
  UserPoolDomain: mud-user-pool
  UserPoolArn: arn:aws:cognito-idp:us-east-1:999999999999:userpool/us-east-1_xxxxxxxxx
Game:
  Balance: 0.25
  AutoSave: 5
  StartingHealth: 10
  StartingEssence: 3
Logging:
  ApplicationName: mud
  LogLevel: 20
  LogGroup: /mud
  LogStream: application
  MetricNamespace: MUD/Application
Server:
  PrivateKeyPath: ./server.key
  Port: 9050
