name: Cloud formation Analysis

on:
  pull_request:
    branches: "**"
  push:
    branches: [develop, qa, prod]

permissions:
  pull-requests: write
  contents: write

jobs:
  evaluate-cloudformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Analysis Tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cfn-lint
      - name: Validate CloudFormation Templates
        run: |
          cfn-lint ./cloudformation/*.yml
