name: Unit-Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: "**"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run tests
        run: |
          git fetch -q
          git checkout ${{github.head_ref}} --progress
          git config --global user.name 'Dark Relics Automatic'
          git config --global user.email 'contact@darkrelics.net'
          git pull
          cd mud
          go vet .
          go test -v ./...
          cd ../database_loader
          go vet .
