name: Unit-Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v4
      
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: 1.21

        - name: Run tests
          run: |
            go get github.com/robinje/multi-user-dungeon
            go test -v ./...